const IMAGES = {
    profileHome : new URL('./profile-1.png', import.meta.url).href,
    profileAbout : new URL('./profile-2.png', import.meta.url).href,
    gowayysia : new URL('./gowayysia.png', import.meta.url).href,
    flory : new URL('./flory.png', import.meta.url).href,
    emptyData : new URL('./empty-data.png', import.meta.url).href,
    figma : new URL('./figma.png', import.meta.url).href,
    uiDesign : new URL('./ui-design.png', import.meta.url).href,
    uxResearch : new URL('./ux-research.png', import.meta.url).href,
    coding : new URL('./coding.png', import.meta.url).href,
    photography : new URL('./photography.png', import.meta.url).href,
    gallery1 : new URL('./gallery-1.jpg', import.meta.url).href,
    gallery2 : new URL('./gallery-2.jpg', import.meta.url).href,
    gallery3 : new URL('./gallery-3.jpg', import.meta.url).href,
    gallery4 : new URL('./gallery-4.jpg', import.meta.url).href,
    gallery5 : new URL('./gallery-5.jpg', import.meta.url).href,
    gallery6 : new URL('./gallery-6.jpg', import.meta.url).href,
    gallery7 : new URL('./gallery-7.jpg', import.meta.url).href,
    gallery8 : new URL('./gallery-8.jpg', import.meta.url).href,
    gallery9 : new URL('./gallery-9.jpg', import.meta.url).href,
    gallery10 : new URL('./gallery-10.jpg', import.meta.url).href,
    gallery11 : new URL('./gallery-11.jpg', import.meta.url).href,
    gallery12 : new URL('./gallery-12.jpg', import.meta.url).href,
    gallery13 : new URL('./gallery-13.jpg', import.meta.url).href,
    gallery14 : new URL('./gallery-14.jpg', import.meta.url).href,
    gallery15 : new URL('./gallery-15.jpg', import.meta.url).href,
    gallery16 : new URL('./gallery-16.jpg', import.meta.url).href,
    gallery17 : new URL('./gallery-17.jpg', import.meta.url).href,
    gallery18 : new URL('./gallery-18.jpg', import.meta.url).href,
    gallery19 : new URL('./gallery-19.jpg', import.meta.url).href,
    gallery20 : new URL('./gallery-20.jpg', import.meta.url).href,
    gallery21 : new URL('./gallery-21.jpg', import.meta.url).href,
}

export default IMAGES
